---
#Install ypbind
- name: Ensure {{ ypbindpkg }} is installed
  yum: 
    name: '{{ ypbindpkg }}'
    state: 'latest'

#Configure yp.conf
- name: Configure yp.conf
  template: 
    src: 'yp.conf.j2' 
    dest: '{{ yp_conf_path }}'
  notify: Restart {{ ypbindsvc }}
