---
#Install ypbind
- name: Ensure {{ ypbind_pkg }} is installed
  yum: 
    name: '{{ ypbind_pkg }}'
    state: 'latest'

#Configure yp.conf
- name: Configure yp.conf
  template: 
    src: 'yp.conf.j2' 
    dest: '{{ yp_conf_path }}'
  notify: Restart {{ ypbindsvc }}
